services:
  app:
    container_name: zi_tomcat
    image: localhost:5000/zucchetti:tmv02
    depends_on:
      - db
    restart: on-failure:3
    ports:
      - '8080:8080'
    networks:
      - frontend
      - backend
    volumes:
      - tomcat_data:/usr/local/tomcat/webapps:rw

  db:
    container_name: zi_postgres
    image: localhost:5000/zucchetti:pgv02
    restart: on-failure:3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} 
    ports:
      - "5432:5432"
    networks:
      - backend      
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw


networks:
  frontend:
    name: zi_frontend
  backend:
    name: zi_backend  
    internal: true


volumes:
  tomcat_data:
    external: false
  postgres_data:
   external: false