FROM postgres:14-bullseye AS db
LABEL authors="MC"
COPY  ./pg/init.sql /docker-entrypoint-initdb.d/init.sql


FROM tomcat:9.0.75-jdk8-temurin-jammy AS app
LABEL authors="MC"
RUN bash -c "cp -avT /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/manager"
RUN apt update && apt-get install -y apt-transport-https
RUN apt install -y ttf-mscorefonts-installer
COPY ./tm/tomcat-users.xml $CATALINA_HOME/conf/tomcat-users.xml
COPY ./tm/manager.xml $CATALINA_HOME/conf/Catalina/localhost/manager.xml
COPY ./tm/host-manager.xml $CATALINA_HOME/conf/Catalina/localhost/host-manager.xml
COPY ./tm/postgresql-42.6.0.jar $CATALINA_HOME/lib/postgresql-42.6.0.jar
COPY ./tm/ahrw41_demo $CATALINA_HOME/webapps/ahrw41_demo
COPY ./tm/DBConfig $CATALINA_HOME/webapps/ahrw41_demo/WEB-INF/classes/DBConfig