  db:
    container_name: zi_postgres
    image: infoservicenet/zucchetti:pgv05
    restart: on-failure:3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} 
    ports:
      - "5432:5432"
    networks:
      - backend      
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
