tomcat:
  container_name: tomcat_9jdk
  image: tomcat:9.0.76-jdk8-temurin-jammy
  restart: on-failure:3
  command: cp -avT $CATALINA_HOME/webapps.dist/manager $CATALINA_HOME/webapps/manager
  ports:
  - '8080:8080'
