FROM tomcat:9.0.81-jdk8-temurin-jammy
COPY configs/tomcat-users.xml /conf/tomcat-users.xml
COPY configs/manager.xml conf/Catalina/localhost/manager.xml
COPY configs/host-manager.xml conf/Catalina/localhost/host-manager.xml
