{
 "title": "PostgreSQL Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DBHost",
    "query": "show tag values on telegraf from pg_backends with key = host"
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Activity Monitor",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rows fetched / returned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Fetched / Returned",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_db_stats",
     "query": "SELECT sum(fetched)  / sum(returned) from\n    (SELECT non_negative_difference(first(\"tup_fetched\")) as fetched, non_negative_difference(first(\"tup_returned\")) as returned FROM \"pg_db_stats\"\n    WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter GROUP BY datname, time($__interval) fill(null))\nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tup_fetched" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "rows_fetched" ], "type": "alias" }
      ],
      [
       { "params": [ "tup_returned" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "rows_returned" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections per database",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_backends",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Connections in Use",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Percentage of max connections in use",
     "measurement": "pg_backends",
     "query": "SELECT max(\"instance_total\") / max(\"max_connections\") FROM \"pg_backends\" WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter group by time($__interval)",
     "select": [
      [
       { "params": [ "instance_total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "max_connections" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Sequential scans vs Index scans",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Sequential scans",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "table_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_table_stats",
     "query": "select sum(seq_scans) from (SELECT non_negative_difference(first(\"seq_scan\")) as seq_scans FROM \"pg_table_stats\" WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter  GROUP BY time($__interval), \"table_name\" fill(none)) group by time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "seq_scan" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    },
    {
     "alias": "Index scans",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(idx_scans) from (SELECT non_negative_difference(first(\"idx_scan\")) as idx_scans FROM \"pg_table_stats\" WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter  GROUP BY time($__interval), \"table_name\" fill(none)) group by time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap-only tuple updates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "table_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_table_stats",
     "query": "select sum(hot_updates) as hot_updates from\n    (SELECT non_negative_difference(first(\"n_tup_hot_upd\")) as hot_updates FROM \"pg_table_stats\" \n    WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter  GROUP BY time($__interval), \"table_name\" fill(none))\ngroup by time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "seq_scan" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Resource Utilization",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 5 tables by disk usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "measurement": "pg_table_stats",
     "select": [
      [
       { "params": [ "table_size_b" ], "type": "field" },
       { "params": [ "table_name, 5" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Temp bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_datname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_db_stats",
     "select": [
      [
       { "params": [ "temp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Rows inserted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "table_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_table_stats",
     "query": "select sum(inserted) as inserted from (SELECT non_negative_difference(first(\"n_tup_ins\")) as inserted FROM \"pg_table_stats\" WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter  GROUP BY time($__interval), \"table_name\" fill(none)) group by time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "seq_scan" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Rows updated",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "table_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_table_stats",
     "query": "select sum(updated) as updated from (SELECT non_negative_difference(first(\"n_tup_upd\")) as updated FROM \"pg_table_stats\" WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter  GROUP BY time($__interval), \"table_name\" fill(none)) group by time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "seq_scan" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Rows deleted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "table_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_table_stats",
     "query": "select sum(deleted) as deleted from (SELECT non_negative_difference(first(\"n_tup_del\")) as deleted FROM \"pg_table_stats\" WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter  GROUP BY time($__interval), \"table_name\" fill(none)) group by time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "seq_scan" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Most frequently scanned indexes",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "index_name" ], "type": "tag" }
     ],
     "measurement": "pg_index_stats",
     "query": "select top(idx_scans, index_name, 5), datname from (SELECT last(\"idx_scan\") - first(\"idx_scan\") as idx_scans FROM \"pg_index_stats\" WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter GROUP BY \"index_name\", \"datname\")",
     "select": [
      [
       { "params": [ "idx_scan" ], "type": "field" },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Least frequently scanned indexes",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "index_name" ], "type": "tag" }
     ],
     "measurement": "pg_index_stats",
     "query": "select bottom(idx_scans, index_name, 5), datname from (SELECT last(\"idx_scan\") - first(\"idx_scan\") as idx_scans FROM \"pg_index_stats\" WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter GROUP BY \"index_name\", \"datname\")",
     "select": [
      [
       { "params": [ "idx_scan" ], "type": "field" },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Locks by lock mode",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_lockmode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lockmode" ], "type": "tag" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_locks_mode",
     "query": "select sum(mean) from \n    (SELECT mean(\"count\") FROM \"pg_locks_mode\" WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter\n    GROUP BY time($__interval), \"lockmode\", \"datname\" fill(null))\nGROUP BY time($__interval), \"lockmode\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Dead Rows",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "table_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pg_table_stats",
     "query": "select sum(last) from (SELECT last(\"n_dead_tup\") FROM \"pg_table_stats\" WHERE (\"host\" =~ /^$DBHost$/) AND $timeFilter GROUP BY time($__interval), \"table_name\" fill(none)) group by time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "n_dead_tup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Top 5 tables by most live rows",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measurement": "pg_table_stats",
     "select": [
      [
       { "params": [ "n_live_tup" ], "type": "field" },
       { "params": [ "table_name, 5" ], "type": "top" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Deadlocks per database",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "datname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pg_db_stats",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DBHost$/" }
     ]
    }
   ]
  }
 ]
}