version: '2'
services:
  app:
    container_name: ${CLIENT}
    image: infoservicenet/zucchetti:tmv05
    restart: on-failure:3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} 
    ports:
      - ${PORT}:8080
    networks:
      - frontend
    volumes:
      - tomcat_data:/usr/local/tomcat/${CLIENT}:rw

  app-config:
    image: infoservicenet/zucchetti:tmv05
    depends_on:
      - app
    restart: "no"
    entrypoint: [ "sh", "-c", "cat << EOF > ./usr/local/tomcat/webapps/ahrw41_demo/WEB-INF/classes/DBConfig.txt
      JDBCConnectionURL.1=jdbc:postgresql://db:5432/${POSTGRES_DB}
      UserName.1=${POSTGRES_USER}
      Password.1=${POSTGRES_PW}
      EOF"]   
      #Armar script en bahs o sh y probar > Probar este punto, no se ejecuta.
networks:
  frontend:
    name: ${CLIENT}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${STAGE_NETWORK_PREFIX}/24
  
volumes:
  tomcat_data:
    external: false