FROM postgres:14-bullseye
ADD  ./pg/init.sql /docker-entrypoint-initdb.d/

FROM postgres:14-bullseye
RUN bash -c "cp -avT $CATALINA_HOME/webapps.dist/manager $CATALINA_HOME/webapps/manager"

#COPY ./mnt/tomcat-users.xml $CATALINA_HOME/conf/
#COPY ./mnt/manager.xml $CATALINA_HOME/conf/Catalina/localhost/
#COPY ./mnt/host-manager.xml $CATALINA_HOME/conf/Catalina/localhost/host-manager.xml
#RUN cp -avT /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/manager
#COPY /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/

