services:
  app:
    container_name: tomcat_zi
    image: tomcat:9.0.76-jdk8-temurin-jammy
    restart: on-failure:3
    ports:
      - '8080:8080'
    networks:
      - frontend


# db:
#    container_name: postgres_zi
#    image: postgres:14-bullseye
#    restart: on-failure:3
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PW}
#      - POSTGRES_DB=${POSTGRES_DB} 
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./pg/init.sql:/docker-entrypoint-initdb.d/init.sql


networks:
  frontend:
    # Use a custom driver
    driver: custom-driver-1
  backend:
    # Use a custom driver which takes special options
    driver: custom-driver-2
    driver_opts:
      foo: "1"
      bar: "2"


volumes:
  tomcat_zi:
    external:
      name: tomcat_zi_data