services:
  app:
    container_name: tomcat_zi
    image: infoservicenet/zucchetti:zi41tcv01
    depends_on:
      - db
    restart: on-failure:3
    ports:
      - '8080:8080'
#    networks:
#      - frontend
    volumes:
      - tomcat_data:/usr/local/tomcat/webapps:rw
#NOTA: Ver si se puede hacer en un solo volumen la data del zucchetti
#     Junto con la data del conector del BD, la libreria y la config del tomcat
#     Para posibles futuros Debugs      

  db:
    container_name: postgres_zi
    image: infoservicenet/zucchetti:zi41pgv01
    restart: on-failure:3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw


#networks:
#  frontend:
#    # Use a custom driver
#    driver: custom-driver-1
#  backend:
#    # Use a custom driver which takes special options
#    driver: custom-driver-2
#    driver_opts:
#      foo: "1"
#      bar: "2"


volumes:
  tomcat_data:
    external: false
  postgres_data:
   external: false