services:
  tomcat:
    container_name: tomcat_zi
    image: tomcat:9.0.76-jdk8-temurin-jammy
    restart: on-failure:3
    ports:
      - '8080:8080'

  postgres:
    container_name: postgres_zi
    image: postgres:14-bullseye
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} 
    ports:
      - "5432:5432"
    volumes:
      - ./pg/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure:3

#networks:
#   frontend:
#   backend:
