version: '3.6'
services:
  telegraf03:
    image: telegrafv03
    container_name: telegraf03
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb
    ports:
    - '8125:8125'
    networks:
      - monitorv02_py27_default