version: '3.6'
services:
  telegraf:
    image: telegrafv02
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf1.conf:ro
    - ./telegraf.conf:/etc/telegraf/telegraf2.conf:ro
    - ./telegraf.conf:/etc/telegraf/telegraf3.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'