FROM postgres:14-bullseye AS db
LABEL authors="MC"
COPY  ./pg/init.sql /docker-entrypoint-initdb.d/init.sql


FROM tomcat:9.0.75-jdk8-temurin-jammy AS app
LABEL authors="MC"
RUN apt update && apt-get install -y apt-transport-https
RUN apt install -y ttf-mscorefonts-installer
RUN bash -c "cp -avT /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/manager"
RUN ln -s /opt/java/openjdk /opt/jdk
RUN ln -s /usr/local/tomcat /opt/tomcat
RUN mkdir /opt/phantomjs
COPY ./tm/phantomjs-2.1.1-linux-x86_64 /opt/phantomjs
COPY ./tm/setenv.sh $CATALINA_HOME/bin/setenv.sh
COPY ./tm/tomcat-users.xml $CATALINA_HOME/conf/tomcat-users.xml
COPY ./tm/manager.xml $CATALINA_HOME/conf/Catalina/localhost/manager.xml
COPY ./tm/host-manager.xml $CATALINA_HOME/conf/Catalina/localhost/host-manager.xml
COPY ./tm/context.xml $CATALINA_HOME/conf/context.xml
COPY ./tm/catalina.properties $CATALINA_HOME/conf/
COPY ./tm/postgresql-42.6.0.jar $CATALINA_HOME/lib/postgresql-42.6.0.jar
COPY ./tm/phantomjs-2.1.1-linux-x86_64 $CATALINA_HOME/webapps/ahrw41_demo/WEB-INF/phantomjs
COPY ./tm/ahrw41_demo $CATALINA_HOME/webapps/ahrw41_demo
COPY ./tm/DBConfig $CATALINA_HOME/webapps/ahrw41_demo/WEB-INF/classes/DBConfig
RUN ln /opt/phantomjs/bin/phantomjs /opt/tomcat/webapps/ahrw41_demo/WEB-INF/phantomjs
RUN chmod 777 -R /opt/phantomjs
RUN ln -s /opt/tomcat/webapps/ahrw41_demo /usr/local/tomcat/webapps/ROOT