version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/config.json
    environment:
      #Only monitor mode - to avoid disrrupt service
      #WATCHTOWER_MONITOR_ONLY: 'true'
      WATCHTOWER_ROLLING_RESTART: 'true'
      WATCHTOWER_TIMEOUT: '30s'
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_POLL_INTERVAL: '86400' 
      WATCHTOWER_DISABLE_CONTAINERS: 'db, portainer, client05'
      ### WATCHTOWER_SCHEDULE: ' ' < Valor String ver docu
      
      #MSTeams Config - Notif 
      ## WATCHTOWER_NOTIFICATIONS: ${WNOT}
      ## WATCHTOWER_NOTIFICATIONS_LEVEL: ${WLVL}
      ## WATCHTOWER_NOTIFICATION_MSTEAMS_HOOK_URL: ${MSWHOOK}

    command: --interval 30 client