version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #Only monitor mode - to avoid disrrupt service
      WATCHTOWER_MONITOR_ONLY: 'true'
      #Email config - notifications
      #WATCHTOWER_NOTIFICATIONS: email
      #WATCHTOWER_NOTIFICATION_EMAIL_FROM: your_gmail
      #WATCHTOWER_NOTIFICATION_EMAIL_TO: recipient_email
      #WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      #WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      ##WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: your_gmail
      #WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: gmail_app_password
      #MSTeams Config - Notif 
      WATCHTOWER_NOTIFICATIONS: ${WNOT}
      WATCHTOWER_NOTIFICATIONS_LEVEL: ${WLVL}
      WATCHTOWER_NOTIFICATION_MSTEAMS_HOOK_URL: ${MSWHOOK}

    command: --interval 30 client01