FROM postgres:14-bullseye AS db
LABEL authors="MC"
COPY  ./pg/init.sql /docker-entrypoint-initdb.d/init.sql


FROM tomcat:9.0.76-jdk8-temurin-jammy AS app
LABEL authors="MC"
RUN bash -c "cp -avT /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/manager"
COPY ./tm/tomcat-users.xml $CATALINA_HOME/conf/tomcat-users.xml
COPY ./tm/manager.xml $CATALINA_HOME/conf/Catalina/localhost/manager.xml
COPY ./tm/host-manager.xml $CATALINA_HOME/conf/Catalina/localhost/host-manager.xml
COPY ./tm/postgresql-42.6.0.jar $CATALINA_HOME/lib/postgresql-42.6.0.jar
COPY ./tm/AHRW41.MOSCATELLI $CATALINA_HOME/webapps/AHRW41.MOSCATELLI
COPY ./tm/DBConfig $CATALINA_HOME/webapps/AHRW41.MOSCATELLI/WEB-INF/classes/DBConfig